puts "\nJRUBY REFERENCES"
puts "**********************"
puts "Getting Started:"
puts "https://github.com/jruby/jruby/wiki/GettingStarted \n\n"
puts "Download:"
puts "http://www.jruby.org/download \n\n"
puts "Examples:"
puts "https://github.com/jruby/jruby/wiki/JRubyAndJavaCodeExamples \n\n"
puts "Misc:"
puts "https://github.com/jruby/jruby/wiki/CallingJavaFromJRuby \n\n"